image: Visual Studio 2017

version: '1.0.{build}'

install:
- dotnet restore src

branches:
      only:
        - master
        - dev
        - /appveyor.*/
    
build:
  project: src\Backpack.SqlBuilder.sln
  verbosity: minimal  
  
configuration: Release
  
artifacts:
  - path: src\Backpack.SqlBuilder\bin\$(configuration)\*.nupkg
    name: Backpack.SqlBuilder_package
